services:
  hello-linux:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: hello-linux:latest  # 构建后镜像的名称和标签
    volumes:
      - .:/root/hello-linux
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
    working_dir: /root/hello-linux
    # sleep infinity 用于保持容器运行，否则 vscode 无法进入容器，建议写在 .devcontainer/docker-compose.yml 文件中
    command: ["sleep", 'infinity']